### ISSUE TITLE
Fix verification from builder bringup script

### ISSUE THREAD

**Issue by AdamSimpson** [AdamSimpson/ContainerBuilder#13]
This should not happen:
```Received build host: Could not find a suitable TLS CA certificate bundle, invalid path: /home/queue/OpenStack.cer:Could not find a suitable TLS CA certificate bundle, invalid path: /home/queue/OpenStack.cer```

**Comment by robertdfrench** [comment]
I have also been able to produce this.

**Comment by AdamSimpson** [comment]
It's what happens when you have specified a bad OS_CACERT on the queue instance
