### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by robertdfrench** [AdamSimpson/ContainerBuilder#8]
https://github.com/AdamSimpson/ContainerBuilder/blob/1aab208710b5d5b095dfb8429ca2c3f79907edcb/Common/src/Messenger.cpp#L84

You have "failbit" and "badbit" but its actually "Fitbit (TM)"

**Comment by robertdfrench** [comment]
Kindly fix this.

**Comment by AdamSimpson** [comment]
Approved
